'use strict';

// telepty#49 — uninstall hygiene. `npm rm -g` used to leave a live daemon (port
// 3848 kept answering), a loaded launchd plist (launchd may resurrect a binary
// that no longer exists), and 3 undocumented state directories behind.
//
// Two entry points share this module:
//   - `telepty uninstall [--purge] [--dry-run]` (cli.js): full pass — stop
//     daemons, unload+remove the launchd plists (macOS), and report the state
//     dirs (kept by default; deleted only with --purge).
//   - scripts/preuninstall.js (npm lifecycle): quiet partial pass — daemon stop
//     + plist unload ONLY, never throws, so `npm rm` can never be broken by it.
//
// Every platform interaction (process cleanup, launchctl, fs) is injectable so
// the logic is unit-testable without touching a live daemon or launchd.

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

// Daemon + broker service labels generated by install.js.
const LAUNCHD_PLIST_NAMES = ['com.aigentry.telepty.plist', 'com.aigentry.telepty-broker.plist'];

function stateDirPaths(homedir) {
  return [
    path.join(homedir, '.telepty'),
    path.join(homedir, '.aigentry'),
    path.join(homedir, '.config', 'aigentry-telepty')
  ];
}

function launchdPlistPaths(homedir) {
  return LAUNCHD_PLIST_NAMES.map((name) => path.join(homedir, 'Library', 'LaunchAgents', name));
}

// What an uninstall on this platform would touch. Pure (no I/O).
function planUninstall(opts = {}) {
  const platform = opts.platform || process.platform;
  const homedir = opts.homedir || os.homedir();
  return {
    platform,
    // launchd is macOS-only; on linux/windows the generated service (systemd
    // unit / scheduled task) is reported as a manual step instead of guessed at.
    plists: platform === 'darwin' ? launchdPlistPaths(homedir) : [],
    stateDirs: stateDirPaths(homedir)
  };
}

function runUninstall(opts = {}) {
  const purge = Boolean(opts.purge);
  const dryRun = Boolean(opts.dryRun);
  const removePlists = opts.removePlists !== false;
  const execFile = opts.execFileSync || execFileSync;
  const fsx = opts.fs || fs;
  // Late-require keeps module load free of side effects and the seam injectable.
  const cleanup = opts.cleanupDaemonProcesses || require('../daemon-control').cleanupDaemonProcesses;
  const plan = planUninstall(opts);

  const result = {
    dryRun,
    purge,
    platform: plan.platform,
    stopped: [],
    failed: [],
    plists: [],
    stateDirs: []
  };

  // (1) Stop running daemons via the full discovery chain (state file →
  // process-title scan → port owner; daemon-control, telepty#15/#44).
  if (!dryRun) {
    try {
      const stopResult = cleanup();
      result.stopped = stopResult.stopped || [];
      result.failed = stopResult.failed || [];
    } catch {
      // Best-effort: a failed scan must not block the rest of the uninstall.
    }
  }

  // (2) launchd service (macOS): unload so launchd stops resurrecting the
  // daemon, then remove the plist file (skipped for the preuninstall hook).
  for (const plistPath of plan.plists) {
    const entry = { path: plistPath, existed: false, unloaded: false, removed: false };
    try {
      entry.existed = fsx.existsSync(plistPath);
    } catch {
      entry.existed = false;
    }
    if (entry.existed && !dryRun) {
      try {
        execFile('launchctl', ['unload', plistPath], { stdio: ['ignore', 'ignore', 'ignore'] });
        entry.unloaded = true;
      } catch {
        entry.unloaded = false; // already unloaded / not loaded — fine either way
      }
      if (removePlists) {
        try {
          fsx.rmSync(plistPath, { force: true });
          entry.removed = true;
        } catch {
          entry.removed = false;
        }
      }
    }
    result.plists.push(entry);
  }

  // (3) State directories: user data stays by default — callers print the
  // paths so the leftover is documented, not silent. Deleted only with --purge.
  for (const dirPath of plan.stateDirs) {
    const entry = { path: dirPath, exists: false, purged: false };
    try {
      entry.exists = fsx.existsSync(dirPath);
    } catch {
      entry.exists = false;
    }
    if (purge && entry.exists && !dryRun) {
      try {
        fsx.rmSync(dirPath, { recursive: true, force: true });
        entry.purged = true;
      } catch {
        entry.purged = false;
      }
    }
    result.stateDirs.push(entry);
  }

  return result;
}

// npm preuninstall lifecycle pass: daemon stop + plist unload only, quietly.
// Never throws — breaking `npm rm` is strictly worse than leaving a daemon.
function runPreuninstall(opts = {}) {
  try {
    return runUninstall({ ...opts, purge: false, dryRun: false, removePlists: false });
  } catch {
    return null;
  }
}

module.exports = {
  LAUNCHD_PLIST_NAMES,
  planUninstall,
  runPreuninstall,
  runUninstall
};
